export const AUTH = "AUTH";
export const ERROR = "ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_UPCOMING_EVENT = "FETCH_UPCOMING_EVENT";
export const FETCH_MAIN_EVENT_MATCH = "FETCH_MAIN_EVENT_MATCH";
// export const FETCH_MATCHES_BY_EVENT_ID = "FETCH_MATCHES_BY_EVENT_ID";
export const FETCH_OUTCOME_METHODS = "FETCH_OUTCOME_METHODS";
export const FETCH_TOPTEN_USERS = "FETCH_TOPTEN_USERS";
export const DELETE = "DELETE";
export const UPDATE_USER = "UPDATE_USER";
export const FETCH_MATCHES = "FETCH_MATCHES";
export const FETCH_ALL_FIGHTERS = "FETCH_ALL_FIGHTERS";
export const ADD_USER = "ADD_USER"
export const FETCH_NETWORKS = "FETCH_NETWORKS";
export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_MATCH = "DELETE_MATCH"
export const FETCH_WEIGHTS = "FETCH_WEIGHTS";
export const ADD_MATCH = "ADD_MATCH";
export const UPDATE_MATCH = "UPDATE_MATCH";
export const ADD_FIGHTER = "ADD_FIGHTER";
export const UPDATE_FIGHTER = "UPDATE_FIGHTER";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_IDLE = "FETCH_EVENTS_IDLE";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";
export const FETCH_UPCOMING_EVENT_SUCCESS = "FETCH_UPCOMING_EVENT_SUCCESS";
export const FETCH_UPCOMING_EVENT_ERROR = "FETCH_UPCOMING_EVENT_ERROR"

export const FETCH_UPCOMING_EVENTS_SUCCESS = "FETCH_UPCOMING_EVENTS_SUCCESS";
export const FETCH_UPCOMING_EVENTS_ERROR = "FETCH_UPCOMING_EVENTS_ERROR";
export const FETCH_UPCOMING_EVENTS = "FETCH_UPCOMING_EVENTS";

export const START_ACTION = "START_ACTION";
export const STOP_ACTION = "STOP_ACTION";
export const REFRESH_ACTION_START = "REFRESH_ACTION_START";
export const REFRESH_ACTION_STOP = "REFRESH_ACTION_STOP";

export const FETCH_MATCHES_BY_EVENT_ID = "FETCH_MATCHES_BY_EVENT_ID";
export const FETCH_MATCHES_BY_EVENT_ID_SUCCESS = "FETCH_MATCHES_BY_EVENT_ID_SUCCESS";
export const FETCH_MATCHES_BY_EVENT_ID_ERROR = "FETCH_MATCHES_BY_EVENT_ID_ERROR"

export const FETCH_UPCOMING_MAIN_EVENT_MATCHES = "FETCH_UPCOMING_MAIN_EVENT_MATCHES";
export const FETCH_UPCOMING_MAIN_EVENT_MATCHES_SUCCESS = "FETCH_UPCOMING_MAIN_EVENT_MATCHES_SUCCESS";
export const FETCH_UPCOMING_MAIN_EVENT_MATCHES_ERROR = "FETCH_UPCOMING_MAIN_EVENT_MATCHES_ERROR";

export const ADD_PICKS = "ADD_PICKS";
export const ADD_PICKS_SUCCESS = "ADD_PICKS_SUCCESS";
export const ADD_PICKS_ERROR = "ADD_PICKS_ERROR";

export const FETCH_UPCOMING_MAIN_EVENTS = "FETCH_UPCOMING_MAIN_EVENTS";
export const FETCH_UPCOMING_MAIN_EVENTS_SUCCESS = "FETCH_UPCOMING_MAIN_EVENTS_SUCCESS";
export const FETCH_UPCOMING_MAIN_EVENTS_ERROR = "FETCH_UPCOMING_MAIN_EVENTS_ERROR";

export const ADMIN_AUTH = "ADMIN_AUTH";
export const ADMIN_ERROR = "ADMIN_ERROR";



